### PR TITLE
Build mulit-arch images

### LINKED ISSUE #16: Build ARM images
**What happened**:
Image build for arm64 is basically images of amd64 arch.

In Dockerfile constant is being used for arch
https://github.com/gardener/apiserver-proxy/blob/904b8f1fa3b2258710e3028e6bfcb7f580a9c57b/cmd/Dockerfile#L7-L8.

**What you expected to happen**:
Images should be able to run on arm64 machine.

**How to reproduce it (as minimally and precisely as possible)**:
Run the below command on an arm64 machine.
```
docker run eu.gcr.io/gardener-project/gardener/apiserver-proxy:v0.4.0-linux-arm64
```
It will fail with following error 
```
exec /apiserver-proxy-sidecar: exec format error
```

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v0.4.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #16

**Special notes for your reviewer**:
I have tested the changes locally and it works as expected. The images I built can be checked. `acuminous/apiserver-proxy:multi-arch`.

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Comment by acumino** [comment]
Images built by pipeline are now multi arch, Check `eu.gcr.io/gardener-project/gardener/apiserver-proxy:v0.5.0-dev-ff6b8cbd202f3bf2aef9d08f5a79ea69e28bc94e`.
Can we have a new release apiserver-proxy? @ScheererJ @DockToFuture

**Comment by ScheererJ** [comment]
@acumino I triggered a release just now.

**Pull request merged**
